### ISSUE TITLE
Use the id in Prestashop as product 

### ISSUE THREAD

**Issue by tildedash** [shoprunback/prestashop-module#101]
# Abstract

Use the prestashop ID for reference and set the prestashop reference in the product metadata if existing

# Details

This will prevent error with chaotic references.

# Requester

@tildedash

**Comment by leo-martin** [comment]
Id for catalogue elements in prestashop are sequentials, it would be better if we generate an Id ourselves instead of using the prestashop Id.

Agreed, the reference can be put in the metadata field
