### ISSUE TITLE
On product duplication, replace the timestamp by the new product's id

### ISSUE THREAD

**Issue by PaulGirardin** [shoprunback/prestashop-module#64]
# Abstract

With an id instead of the timestamp, the admin will more easily see which product corresponds to which after the duplication.

# Details

#53 

# Requester

@tildedash

**Comment by tildedash** [comment]
@PaulGirardin by the way the ID is immutable not the timestamp,

depending of the time you synchronize with your timestamp solution will create a new reference.

With the id, it will always return the same string
